name: Build

on: 
 push:
    tags:
      - 'v0.*'
      - 'draft-*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          clean: false
          submodules: "recursive"
      - run: |
          git fetch --prune --unshallow --tags

      - name: Build and Release
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean  --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          
      - name: Archive files
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: dist/*.zip

      - name: Archive files
        uses: actions/upload-artifact@v2
        with:
          name: linux
          path: dist/*.gz

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files:  dist/*
          draft: true
          fail_on_unmatched_files: true
